### ISSUE TITLE
Go To Definition Inconsistent

### ISSUE THREAD

**Issue by carrola1** [eirikpre/VSCode-SystemVerilog#55] opened 2019-07-19 13:07 UTC
Great extension! I've found the go to definition feature does not always work. I can jump to a module definition successfully, go back to the original file, try again, and it no longer works. After playing around a bit i found that if i save a file before using go to definition it works every time.

**Comment by eirikpre** [comment] 2019-07-24 12:40
Hm that is strange, big changes have been done to the backend storage of the symbols, namely also that they will update accordingly when a file is saved.
Will try to reproduce when vacation ends next week

**Comment by eirikpre** [comment] 2019-09-05 15:21
I have not been able to reproduce this error, is it still a problem?
Since then, I changed many of the types to built-in standard types, which may have solved your problem.

**Comment by mahsoommoosa42** [comment] 2019-10-27 13:13
I am facing this problem. Support for definitions is very erratic and it doesn't work most of the time. And I think the number of indexed objects is way less than there actually is. Btw, great extension. Real life-saver.

**Comment by eirikpre** [comment] 2019-10-28 13:22
Mhm, that is interesting, I did not find any way to figure out what are missing.
I would probably guess that you are not getting definitions for signals in the port list inside the module.
I'm in the process of adding that, but I'm kinda waiting for this Code issue: https://github.com/microsoft/vscode/issues/53034 
(because outline will explode when adding the ports to it)

**Comment by eirikpre** [comment] 2019-10-28 13:27
And the parser isn't that clever, it will not understand multiple declared variables on one line for example.
```
logic will, not, understand;
```
vs
```
logic will;
logic understand;
```

If you are familiar with regexes, this the matcher looking for instantiated objects: 
https://github.com/eirikpre/VSCode-SystemVerilog/blob/master/src/parser.ts#L52

**Comment by mahsoommoosa42** [comment] 2019-10-28 13:57
I just debugged the extension. this.symbolsCount returns 79 but, when i checked the contents of this.symbols. Only 22 objects were present within and only the names of the modules in my files. The signals within these modules were not present (even for my currently open file).

**Comment by eirikpre** [comment] 2019-10-28 15:45
Yeah, this.symbols would be a list of files containing modules. So you might have multiple modules per file, but that shouldn't be a problem

**Comment by mahsoommoosa42** [comment] 2019-10-28 16:09
Yes, but within them I believe only the modules are listed. Go to definition works on instantiated modules but not on any of the other objects.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by mahsoommoosa42** [comment] 2019-10-28 20:30
I'll test with the new commit and see if it does the trick.

**Comment by eirikpre** [comment] 2019-10-29 07:23
It is primarily modules that will be indexed, but depending on the size of the workspace, it will index packages, classes, macros, ++ and 1 level of hierarchy (eg. class within package, functions within class).

I will try to rewrite the regex looking for symbols to include multiple declared signals, and then release on the marketplace.

**Comment by mahsoommoosa42** [comment] 2019-10-29 13:42
Okay. Didn't notice that the extension doesn't index signals. Let me know if you require assistance. More than happy to contribute.

**Comment by eirikpre** [comment] 2019-11-01 13:43
@mahsoommoosa42 I published the changes which should match a lot more symbols. Tell me if you if(when?) encounter any issues, or if there is something you are particularly interested in contributing to.

**Closed by eirikpre** 2019-11-01 13:43 UTC
Labels: question

**Comment by mahsoommoosa42** [comment] 2019-11-06 07:18
Working great on first look
