### ISSUE TITLE
begin...end style auto alignment missing for other pairs

### ISSUE THREAD

**Issue by n-badri** [eirikpre/VSCode-SystemVerilog#7] opened 2018-02-05 11:28 UTC
just like how begin...end auto aligns along the same column, other bracketed words like module...endmodule, task..endtask should automatically align along the same column

**Comment by eirikpre** [comment] 2018-05-29 11:27
I've been experimenting a bit, and it seems to work just fine. Closing because I could not reproduce

**Closed by eirikpre** 2018-05-29 11:27 UTC
